### ISSUE TITLE
Please add background color for selected item

### ISSUE THREAD

**Issue by Nriver** [greengeek/trilium-vscode-dark-theme#2]
When I @ a note to create a internal link, the popup menu does not emphasize the item with a different color.

**Comment by greengeek** [comment]
Should now be fixed.  Please let me know if you still see any issues.

https://github.com/greengeek/trilium-vscode-dark-theme/commit/0d397d459839c7e4da7697663374f742696027e7

**Comment by greengeek** [comment]
Fixed in https://github.com/greengeek/trilium-vscode-dark-theme/commit/0d397d459839c7e4da7697663374f742696027e7

**Comment by Nriver** [comment]
Oh, I see you fixed the mouse hover. But what I mean was using the arrow keys to navigate through the popup menu.

**Comment by Nriver** [comment]
There is a different background as you just type @ without moving the mouse in the built-in themes.

**Comment by greengeek** [comment]
I understand now.  I think I fixed it.  Please let me know.

**Comment by greengeek** [comment]
fixed

**Comment by Nriver** [comment]
Looks great now, thanks!
